name: docscanner
description: Una aplicación para escanear documentos con detección automática de bordes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  google_fonts: ^4.0.4
  image: ^4.0.17
  image_picker: ^1.0.7
  permission_handler: ^11.0.1
  flutter_image_compress: ^2.0.3
  provider: ^6.1.1
  share_plus: ^7.2.1
  google_mlkit_commons: 0.9.0 
  google_mlkit_text_recognition: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/scanner_icon.png
    - assets/images/image.jpeg
